name: Run Python Test

on:
  push:
    branches:
      - main

jobs:
  branch_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Python script
      run: |
       python3 trabalho3/branch_1/script_senha_correta.py  

  branch_2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Run Python script
      run: |
       python3 trabalho3/branch_2/script_senha_correta.py  
